version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          keys:
            - sls-seed-plugin-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: sls-seed-plugin-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Run Linter
          command: npm run lint
      - run:
          name: Run Tests
          command: npm run test

workflows:
  version: 2
  test:
    jobs:
      - test
